/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Firebase.UserLoginToken;
import Database.ClientDatabase;
import Database.Dataclass.ClientData;
import Database.Exception.DatabaseGetInterrupted;
import EmailService.EmailSender;
import Form.Admin.AdminLanding;
import Form.User.AboutDeveloper;
import Form.User.UserLanding;
import Utility.PasswordGenerator;
import jakarta.mail.MessagingException;
import javax.swing.*;
import java.awt.*;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;

/**
 *
 * @author Nonsan
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stud_id_tf = new javax.swing.JTextField();
        pass_tf = new javax.swing.JPasswordField();
        signin_btn = new javax.swing.JButton();
        fgt_pass = new javax.swing.JLabel();
        fgt_pass1 = new javax.swing.JLabel();
        signup_btn = new javax.swing.JLabel();
        contacttext = new javax.swing.JLabel();
        contact_btn = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        name_th_tf = new javax.swing.JTextField();
        surname_th_tf = new javax.swing.JTextField();
        name_en_tf = new javax.swing.JTextField();
        surname_en_tf = new javax.swing.JTextField();
        email_tf = new javax.swing.JTextField();
        password_tf = new javax.swing.JPasswordField();
        c_password_tf = new javax.swing.JPasswordField();
        student_id_tf = new javax.swing.JTextField();
        register_btn = new javax.swing.JButton();
        ForgetPasswordPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        forget_studid = new javax.swing.JTextField();
        forget_email = new javax.swing.JTextField();
        forgetpass_btn = new javax.swing.JButton();
        backbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BookITNow");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        MainPanel.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(21, 31, 44));

        jPanel1.setBackground(new java.awt.Color(21, 31, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/test_logo.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("FreesiaUPC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ยินดีต้อนรับ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("FreesiaUPC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ลงชื่อเข้าใช้");

        stud_id_tf.setBackground(new java.awt.Color(34, 34, 34));
        stud_id_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 24)); // NOI18N
        stud_id_tf.setForeground(new java.awt.Color(117, 105, 109));
        stud_id_tf.setText("รหัสนักศึกษา / Student ID");
        stud_id_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stud_id_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stud_id_tfFocusLost(evt);
            }
        });

        pass_tf.setBackground(new java.awt.Color(34, 34, 34));
        pass_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 24)); // NOI18N
        pass_tf.setForeground(new java.awt.Color(117, 105, 109));
        pass_tf.setText("รหัสผ่าน / Password");
        pass_tf.setEchoChar((char) 0);
        pass_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_tfFocusLost(evt);
            }
        });

        signin_btn.setBackground(new java.awt.Color(0, 0, 0));
        signin_btn.setFont(new java.awt.Font("FreesiaUPC", 1, 30)); // NOI18N
        signin_btn.setForeground(new java.awt.Color(255, 255, 255));
        signin_btn.setText("ลงชื่อเข้าใช้");
        signin_btn.setToolTipText("");
        signin_btn.setBorderPainted(false);
        signin_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_btn.setFocusPainted(false);
        signin_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signin_btn.putClientProperty("JButton.buttonType", "roundRect");
        signin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_btnActionPerformed(evt);
            }
        });

        fgt_pass.setFont(new java.awt.Font("FreesiaUPC", 0, 26)); // NOI18N
        fgt_pass.setForeground(new java.awt.Color(117, 105, 109));
        fgt_pass.setText("ลืมรหัสผ่าน?");
        fgt_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgt_passMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgt_passMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgt_passMouseExited(evt);
            }
        });

        fgt_pass1.setFont(new java.awt.Font("FreesiaUPC", 0, 26)); // NOI18N
        fgt_pass1.setForeground(new java.awt.Color(117, 105, 109));
        fgt_pass1.setText("ยังไม่เคยลงทะเบียน?");
        fgt_pass1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        signup_btn.setFont(new java.awt.Font("FreesiaUPC", 0, 26)); // NOI18N
        signup_btn.setForeground(new java.awt.Color(117, 105, 109));
        signup_btn.setText("ลงทะเบียนเลย!");
        signup_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signup_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signup_btnMouseExited(evt);
            }
        });

        contacttext.setFont(new java.awt.Font("FreesiaUPC", 0, 26)); // NOI18N
        contacttext.setForeground(new java.awt.Color(117, 105, 109));
        contacttext.setText("ติดปัญหา? ");
        contacttext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        contact_btn.setFont(new java.awt.Font("FreesiaUPC", 0, 26)); // NOI18N
        contact_btn.setForeground(new java.awt.Color(117, 105, 109));
        contact_btn.setText(" ติดต่อผู้พัฒนา");
        contact_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contact_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contact_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contact_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contact_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fgt_pass, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(signin_btn, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                        .addComponent(fgt_pass1)
                        .addGap(8, 8, 8)
                        .addComponent(signup_btn))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stud_id_tf, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_tf, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contacttext)
                .addGap(8, 8, 8)
                .addComponent(contact_btn)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(signin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(fgt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fgt_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacttext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainPanel.add(LoginPanel, "LoginPanel");

        RegisterPanel.setBackground(new java.awt.Color(21, 31, 44));

        backbtn.setFont(new java.awt.Font("Unispace", 0, 48)); // NOI18N
        backbtn.setForeground(new java.awt.Color(117, 105, 109));
        backbtn.setText("<");
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setContentAreaFilled(false);
        backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbtn.setFocusPainted(false);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/test_logo_noraptor.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("FreesiaUPC", 1, 76)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ลงทะเบียน");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("FreesiaUPC", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("กรุณากรอกข้อมูลให้ถูกต้องและครบถ้วน");

        jPanel2.setBackground(new java.awt.Color(21, 31, 44));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 34, 34), 5, true));

        name_th_tf.setBackground(new java.awt.Color(34, 34, 34));
        name_th_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        name_th_tf.setForeground(new java.awt.Color(117, 105, 109));
        name_th_tf.setText("ชื่อจริง (ภาษาไทย)");
        name_th_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_th_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_th_tfFocusLost(evt);
            }
        });

        surname_th_tf.setBackground(new java.awt.Color(34, 34, 34));
        surname_th_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        surname_th_tf.setForeground(new java.awt.Color(117, 105, 109));
        surname_th_tf.setText("นามสกุล (ภาษาไทย)");
        surname_th_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surname_th_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                surname_th_tfFocusLost(evt);
            }
        });

        name_en_tf.setBackground(new java.awt.Color(34, 34, 34));
        name_en_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        name_en_tf.setForeground(new java.awt.Color(117, 105, 109));
        name_en_tf.setText("ชื่อจริง (ภาษาอังกฤษ)");
        name_en_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_en_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_en_tfFocusLost(evt);
            }
        });

        surname_en_tf.setBackground(new java.awt.Color(34, 34, 34));
        surname_en_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        surname_en_tf.setForeground(new java.awt.Color(117, 105, 109));
        surname_en_tf.setText("นามสกุล (ภาษาอังกฤษ)");
        surname_en_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surname_en_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                surname_en_tfFocusLost(evt);
            }
        });

        email_tf.setBackground(new java.awt.Color(34, 34, 34));
        email_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        email_tf.setForeground(new java.awt.Color(117, 105, 109));
        email_tf.setText("E-mail");
        email_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_tfFocusLost(evt);
            }
        });

        password_tf.setBackground(new java.awt.Color(34, 34, 34));
        password_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        password_tf.setForeground(new java.awt.Color(117, 105, 109));
        password_tf.setText("รหัสผ่าน");
        password_tf.setEchoChar((char) 0);
        password_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_tfFocusLost(evt);
            }
        });

        c_password_tf.setBackground(new java.awt.Color(34, 34, 34));
        c_password_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        c_password_tf.setForeground(new java.awt.Color(117, 105, 109));
        c_password_tf.setText("ยืนยันรหัสผ่าน");
        c_password_tf.setEchoChar((char) 0);
        c_password_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c_password_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_password_tfFocusLost(evt);
            }
        });

        student_id_tf.setBackground(new java.awt.Color(34, 34, 34));
        student_id_tf.setFont(new java.awt.Font("FreesiaUPC", 0, 30)); // NOI18N
        student_id_tf.setForeground(new java.awt.Color(117, 105, 109));
        student_id_tf.setText("รหัสนักศึกษา");
        student_id_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                student_id_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                student_id_tfFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(student_id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(c_password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(name_en_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(surname_en_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(name_th_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(surname_th_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_th_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname_th_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_en_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname_en_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(student_id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        register_btn.setBackground(new java.awt.Color(0, 0, 0));
        register_btn.setFont(new java.awt.Font("FreesiaUPC", 1, 48)); // NOI18N
        register_btn.setForeground(new java.awt.Color(255, 255, 255));
        register_btn.setText("ลงทะเบียน");
        register_btn.setBorderPainted(false);
        register_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_btn.setFocusPainted(false);
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        MainPanel.add(RegisterPanel, "RegisterPanel");

        ForgetPasswordPanel.setBackground(new java.awt.Color(21, 31, 44));

        jPanel3.setBackground(new java.awt.Color(21, 31, 44));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("FreesiaUPC", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("กดเพื่อรีเซตรหัสผ่าน");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("FreesiaUPC", 1, 76)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("รหัสผ่านจะส่งไปยังอีเมลของท่าน");

        forget_studid.setBackground(new java.awt.Color(34, 34, 34));
        forget_studid.setFont(new java.awt.Font("FreesiaUPC", 0, 36)); // NOI18N
        forget_studid.setForeground(new java.awt.Color(117, 105, 109));
        forget_studid.setText("รหัสนักศึกษา / Student ID");
        forget_studid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                forget_studidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                forget_studidFocusLost(evt);
            }
        });

        forget_email.setBackground(new java.awt.Color(34, 34, 34));
        forget_email.setFont(new java.awt.Font("FreesiaUPC", 0, 36)); // NOI18N
        forget_email.setForeground(new java.awt.Color(117, 105, 109));
        forget_email.setText("อีเมล / E-mail");
        forget_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                forget_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                forget_emailFocusLost(evt);
            }
        });

        forgetpass_btn.setBackground(new java.awt.Color(0, 0, 0));
        forgetpass_btn.setFont(new java.awt.Font("FreesiaUPC", 1, 48)); // NOI18N
        forgetpass_btn.setForeground(new java.awt.Color(255, 255, 255));
        forgetpass_btn.setText("รีเซ็ตรหัสผ่าน");
        forgetpass_btn.setBorderPainted(false);
        forgetpass_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetpass_btn.setFocusPainted(false);
        forgetpass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetpass_btnActionPerformed(evt);
            }
        });

        backbtn1.setFont(new java.awt.Font("Unispace", 0, 48)); // NOI18N
        backbtn1.setForeground(new java.awt.Color(117, 105, 109));
        backbtn1.setText("<");
        backbtn1.setBorder(null);
        backbtn1.setBorderPainted(false);
        backbtn1.setContentAreaFilled(false);
        backbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbtn1.setFocusPainted(false);
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(125, 125, 125))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbtn1)
                        .addGap(327, 327, 327)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(forget_studid, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forget_email, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forgetpass_btn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(backbtn1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forget_studid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forget_email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forgetpass_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ForgetPasswordPanelLayout = new javax.swing.GroupLayout(ForgetPasswordPanel);
        ForgetPasswordPanel.setLayout(ForgetPasswordPanelLayout);
        ForgetPasswordPanelLayout.setHorizontalGroup(
            ForgetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ForgetPasswordPanelLayout.setVerticalGroup(
            ForgetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainPanel.add(ForgetPasswordPanel, "ForgetPasswordPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1014, 834));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stud_id_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stud_id_tfFocusGained
        System.out.println("StudGainFocus");
        if (stud_id_tf.getText().equals("รหัสนักศึกษา / Student ID")){
            stud_id_tf.setText("");
            stud_id_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_stud_id_tfFocusGained

    private void stud_id_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stud_id_tfFocusLost
        System.out.println("StudLostFocus");
        if (stud_id_tf.getText().isEmpty()){
            stud_id_tf.setText("รหัสนักศึกษา / Student ID");
            stud_id_tf.setForeground(tf_lostFocus_color);
       }
    }//GEN-LAST:event_stud_id_tfFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void pass_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_tfFocusGained
        System.out.println("Password GainedFocus");
        if (pass_tf.getText().equals("รหัสผ่าน / Password")){
            pass_tf.setText("");
            pass_tf.setEchoChar('*');
            pass_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_pass_tfFocusGained

    private void pass_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_tfFocusLost
        System.out.println("Password LostFocus");
        if (pass_tf.getText().isEmpty()){
            pass_tf.setText("รหัสผ่าน / Password");
            pass_tf.setEchoChar((char) 0);
            pass_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_pass_tfFocusLost

    private void fgt_passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgt_passMouseEntered
        fgt_pass.setForeground(new Color(72, 145, 255));
    }//GEN-LAST:event_fgt_passMouseEntered

    private void fgt_passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgt_passMouseExited
        fgt_pass.setForeground(tf_lostFocus_color);
    }//GEN-LAST:event_fgt_passMouseExited

    private void signup_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_btnMouseEntered
        signup_btn.setForeground(new Color(72, 145, 255));
    }//GEN-LAST:event_signup_btnMouseEntered

    private void signup_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_btnMouseExited
        signup_btn.setForeground(tf_lostFocus_color);
    }//GEN-LAST:event_signup_btnMouseExited

    private void contact_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contact_btnMouseEntered
        contact_btn.setForeground(new Color(72, 145, 255));
    }//GEN-LAST:event_contact_btnMouseEntered

    private void contact_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contact_btnMouseExited
        contact_btn.setForeground(tf_lostFocus_color);
    }//GEN-LAST:event_contact_btnMouseExited

    private void signup_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_btnMouseClicked
            java.awt.CardLayout cardLayout = ( java.awt.CardLayout) MainPanel.getLayout();
            cardLayout.show(MainPanel, "RegisterPanel");
    }//GEN-LAST:event_signup_btnMouseClicked

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        java.awt.CardLayout cardLayout = ( java.awt.CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "LoginPanel");
        resetRegTF();
    }//GEN-LAST:event_backbtnActionPerformed

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
        //variable assign
        String name_th = name_th_tf.getText();
        String surname_th = surname_th_tf.getText();
        String name_en = name_en_tf.getText();
        String surname_en = surname_en_tf.getText();
        String email = email_tf.getText();
        String student_id = student_id_tf.getText();
        char[] password = password_tf.getPassword();
        char[] c_password = c_password_tf.getPassword();

        String check_status = validateUserInput(name_th, surname_th, name_en, surname_en, email, student_id, password, c_password);
        if (check_status.equals("Pass")){
            // register user to the database
            if(ClientDatabase.register(name_th, surname_th, name_en, surname_en, email, student_id, password)){

                // take user back to the login gui
                java.awt.CardLayout cardLayout = ( java.awt.CardLayout) MainPanel.getLayout();
                cardLayout.show(MainPanel, "LoginPanel");
                resetRegTF();
                // create a result dialog
                JOptionPane.showMessageDialog(LoginGUI.this,"Register Successful.");
            }else{
                // register failed (likely due to the user already existing in the database)
                JOptionPane.showMessageDialog(LoginGUI.this,"This Student ID is already taken.");
            }
        } else {
            JOptionPane.showMessageDialog(LoginGUI.this, check_status);
        }

    }//GEN-LAST:event_register_btnActionPerformed

    private void name_thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_thActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_thActionPerformed

    private void name_th_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_thFocusGained
        if (name_th_tf.getText().equals("ชื่อจริง (ภาษาไทย)")) {
            name_th_tf.setText("");
            name_th_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_name_thFocusGained

    private void name_th_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_thFocusLost
         if (name_th_tf.getText().isEmpty()) {
            name_th_tf.setText("ชื่อจริง (ภาษาไทย)");
            name_th_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_name_thFocusLost

    private void surname_th_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surname_thFocusGained
        if (surname_th_tf.getText().equals("นามสกุล (ภาษาไทย)")) {
            surname_th_tf.setText("");
            surname_th_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_surname_thFocusGained

    private void surname_th_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surname_thFocusLost
        if (surname_th_tf.getText().isEmpty()) {
            surname_th_tf.setText("นามสกุล (ภาษาไทย)");
            surname_th_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_surname_thFocusLost

    private void name_en_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_enFocusGained
        if (name_en_tf.getText().equals("ชื่อจริง (ภาษาอังกฤษ)")) {
            name_en_tf.setText("");
            name_en_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_name_enFocusGained

    private void name_en_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_enFocusLost
        if (name_en_tf.getText().isEmpty()) {
            name_en_tf.setText("ชื่อจริง (ภาษาอังกฤษ)");
            name_en_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_name_enFocusLost

    private void surname_en_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surname_enFocusGained
        if (surname_en_tf.getText().equals("นามสกุล (ภาษาอังกฤษ)")) {
            surname_en_tf.setText("");
            surname_en_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_surname_enFocusGained

    private void surname_en_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surname_enFocusLost
        if (surname_en_tf.getText().isEmpty()) {
            surname_en_tf.setText("นามสกุล (ภาษาอังกฤษ)");
            surname_en_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_surname_enFocusLost

    private void email_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_tfFocusGained
        if (email_tf.getText().equals("E-mail")) {
            email_tf.setText("");
            email_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_email_tfFocusGained

    private void email_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_tfFocusLost
        if (email_tf.getText().isEmpty()) {
            email_tf.setText("E-mail");
            email_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_email_tfFocusLost

    private void password_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if (new String(password_tf.getPassword()).equals("รหัสผ่าน")){
            password_tf.setText("");
            password_tf.setEchoChar('*');
            password_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_passwordFocusGained

    private void password_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
         if (new String(password_tf.getPassword()).isEmpty()){
            password_tf.setText("รหัสผ่าน");
            password_tf.setEchoChar((char) 0);
            password_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_passwordFocusLost

    private void c_password_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_passwordFocusGained
        if (new String(c_password_tf.getPassword()).equals("ยืนยันรหัสผ่าน")){
            c_password_tf.setText("");
            c_password_tf.setEchoChar('*');
            c_password_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_c_passwordFocusGained

    private void c_password_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_passwordFocusLost
        if (new String(c_password_tf.getPassword()).isEmpty()){
            c_password_tf.setText("ยืนยันรหัสผ่าน");
            c_password_tf.setEchoChar((char) 0);
            c_password_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_c_passwordFocusLost

    private void student_id_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_student_idFocusGained
        if (student_id_tf.getText().equals("รหัสนักศึกษา")) {
            student_id_tf.setText("");
            student_id_tf.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_student_idFocusGained

    private void student_id_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_student_idFocusLost
         if (student_id_tf.getText().isEmpty()) {
            student_id_tf.setText("รหัสนักศึกษา");
            student_id_tf.setForeground(tf_lostFocus_color);
        }
    }//GEN-LAST:event_student_idFocusLost

    private void forget_studidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_forget_studidFocusGained
        if (forget_studid.getText().equals("รหัสนักศึกษา / Student ID")){
            forget_studid.setText("");
            forget_studid.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_forget_studidFocusGained

    private void forget_studidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_forget_studidFocusLost
        if (forget_studid.getText().isEmpty()){
            forget_studid.setText("รหัสนักศึกษา / Student ID");
            forget_studid.setForeground(tf_lostFocus_color);
       }
    }//GEN-LAST:event_forget_studidFocusLost

    private void forget_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_forget_emailFocusGained
        if (forget_email.getText().equals("อีเมล / E-mail")){
            forget_email.setText("");
            forget_email.setForeground(tf_Focus_color);
        }
    }//GEN-LAST:event_forget_emailFocusGained

    private void forget_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_forget_emailFocusLost
        if (forget_email.getText().isEmpty()){
            forget_email.setText("อีเมล / E-mail");
            forget_email.setForeground(tf_lostFocus_color);
       }
    }//GEN-LAST:event_forget_emailFocusLost

    private void fgt_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgt_passMouseClicked
        java.awt.CardLayout cardLayout = ( java.awt.CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "ForgetPasswordPanel");
    }//GEN-LAST:event_fgt_passMouseClicked

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn1ActionPerformed
        java.awt.CardLayout cardLayout = ( java.awt.CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "LoginPanel");
        forget_studid.setText("รหัสนักศึกษา / Student ID");
        forget_email.setText("อีเมล / E-mail");
        forget_studid.setForeground(tf_lostFocus_color);
        forget_email.setForeground(tf_lostFocus_color);
    }//GEN-LAST:event_backbtn1ActionPerformed

    private void forgetpass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetpass_btnActionPerformed
        String std_id = forget_studid.getText();
        String email = forget_email.getText();
        if (!std_id.isEmpty() && !email.isEmpty() && !std_id.equals("รหัสนักศึกษา / Student ID") && !email.equals("อีเมล / E-mail")){
            if (ClientDatabase.checkUserExist(std_id)) {
                try {
                    if (email.equals(ClientDatabase.getClientObject(std_id).getEmail())) {
                        try {
                            String new_pass = PasswordGenerator.generatePassword(12, true, true, true);
                            new EmailSender(email, "This is your new password " + new_pass + "\nPlease change your password to new one.");
                            ClientDatabase.updateClient(std_id, "passcode", ClientData.hashing(new_pass));
                            JOptionPane.showMessageDialog(LoginGUI.this, "Reset Password Successful!\nPlease check your mailbox.");
                            java.awt.CardLayout cardLayout = ( java.awt.CardLayout) MainPanel.getLayout();
                            cardLayout.show(MainPanel, "LoginPanel");
                            forget_studid.setText("รหัสนักศึกษา / Student ID");
                            forget_email.setText("อีเมล / E-mail");
                            forget_studid.setForeground(tf_lostFocus_color);
                            forget_email.setForeground(tf_lostFocus_color);
                        } catch (MessagingException | UnsupportedEncodingException ex) {
                            JOptionPane.showMessageDialog(LoginGUI.this, ex.getMessage());
                        }
                    } else {
                        JOptionPane.showMessageDialog(LoginGUI.this, "Incorrect Email.");
                    }
                } catch (DatabaseGetInterrupted ex) {
                    JOptionPane.showMessageDialog(LoginGUI.this, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(LoginGUI.this, "Incorrect Student ID.");
            }
        } else {
            JOptionPane.showMessageDialog(LoginGUI.this, "Please fill empty container.");
        }


    }//GEN-LAST:event_forgetpass_btnActionPerformed

    private void contact_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contact_btnMouseClicked
        AboutDeveloper aboutDeveloper = new AboutDeveloper();
        aboutDeveloper.setVisible(true);
        aboutDeveloper.setAlwaysOnTop(true);
    }//GEN-LAST:event_contact_btnMouseClicked

    private void signin_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String stud_id = stud_id_tf.getText();

        if (validateLoginInput(stud_id, new String(pass_tf.getPassword()))){
            if (ClientDatabase.validateLogin(stud_id_tf.getText(), new String(pass_tf.getPassword()))) {
                try {
                    UserLoginToken.loginUser(ClientDatabase.getClientObject(stud_id));
                    this.dispose();
                    UserLanding userLanding = new UserLanding();
                    userLanding.setVisible(true);
                    userLanding.setLocationRelativeTo(null);
                } catch (DatabaseGetInterrupted dgi){
                    JOptionPane.showMessageDialog(LoginGUI.this, dgi.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(LoginGUI.this, "Incorrect Student ID/ Password.");
            }
        } else {
            JOptionPane.showMessageDialog(LoginGUI.this, "Please fill out every field / Incorrect Student ID.");
        }

    }
    private boolean validateLoginInput(String stud_id, String password){
        return !stud_id.isEmpty() && !password.isEmpty() && !stud_id.equals("รหัสนักศึกษา / Student ID") && !password.equals("รหัสผ่าน / Password")
                && stud_id.length() == 8;
    }
    private String validateUserInput(String name_th, String surname_th, String name_en, String surname_en, String email, String stud_id,
                                     char[] password, char[] rePassword) {
        // All fields must have a value
        if (name_th.isEmpty() || surname_th.isEmpty() || name_en.isEmpty() || surname_en.isEmpty() || email.isEmpty() || stud_id.isEmpty() || password.length == 0 || rePassword.length == 0
            || name_th.equals(df_name_th) || surname_th.equals(df_surname_th) || name_en.equals(df_name_en) || surname_en.equals(df_surname_en) || email.equals(df_email)
                || stud_id.equals(df_stud_id) || Arrays.equals(password, df_password.toCharArray()) || Arrays.equals(rePassword, df_c_password.toCharArray())){
            return "Please fill out every container.";
        }

        // Name fields must be at least 2 characters long
        if (name_th.length() < 2 || surname_th.length() < 2 || name_en.length() < 2 || surname_en.length() < 2) {
            return "Name are not long enough.";
        }

        // Password must be at least 6 characters long
        if (password.length < 6 || password.length > 60) {
            return "Password must be at least 6 characters long / Maximum 60.";
        }

        // Password and rePassword must be the same
        if (!Arrays.equals(password, rePassword)) {
            return "Password does not match.";
        }

        // Email validation (simple check for '@' and '.' characters)
        if (!email.contains("@") || !email.contains(".")) {
            return "Incorrect email formation.";
        }

        // Student ID validation (assuming a specific format, e.g., 6 digits)
        if (stud_id.length() != 8 || !stud_id.matches("\\d+")) {
            return "Incorrect Student ID.";
        }

        // Passes validation
        return "Pass";
    }

    private void resetRegTF(){
        name_th_tf.setText(df_name_th);
        name_th_tf.setForeground(tf_lostFocus_color);
        surname_th_tf.setText(df_surname_th);
        surname_th_tf.setForeground(tf_lostFocus_color);
        name_en_tf.setText(df_name_en);
        name_en_tf.setForeground(tf_lostFocus_color);
        surname_en_tf.setText(df_surname_en);
        surname_en_tf.setForeground(tf_lostFocus_color);
        email_tf.setText(df_email);
        email_tf.setForeground(tf_lostFocus_color);
        student_id_tf.setText(df_stud_id);
        student_id_tf.setForeground(tf_lostFocus_color);
        password_tf.setText(df_password);
        password_tf.setForeground(tf_lostFocus_color);
        c_password_tf.setText(df_c_password);
        c_password_tf.setForeground(tf_lostFocus_color);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ForgetPasswordPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton backbtn1;
    private javax.swing.JPasswordField c_password_tf;
    private javax.swing.JLabel contact_btn;
    private javax.swing.JLabel contacttext;
    private javax.swing.JTextField email_tf;
    private javax.swing.JLabel fgt_pass;
    private javax.swing.JLabel fgt_pass1;
    private javax.swing.JTextField forget_email;
    private javax.swing.JTextField forget_studid;
    private javax.swing.JButton forgetpass_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField name_en_tf;
    private javax.swing.JTextField name_th_tf;
    private javax.swing.JPasswordField pass_tf;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JButton register_btn;
    private javax.swing.JButton signin_btn;
    private javax.swing.JLabel signup_btn;
    private javax.swing.JTextField stud_id_tf;
    private javax.swing.JTextField student_id_tf;
    private javax.swing.JTextField surname_en_tf;
    private javax.swing.JTextField surname_th_tf;
    // End of variables declaration//GEN-END:variables

    //default tf text
    private final String df_name_th = "ชื่อจริง (ภาษาไทย)";
    private final String df_surname_th = "นามสกุล (ภาษาไทย)";
    private final String df_name_en = "ชื่อจริง (ภาษาอังกฤษ)";
    private final String df_surname_en = "นามสกุล (ภาษาอังกฤษ)";
    private final String df_email = "E-mail";
    private final String df_stud_id = "รหัสนักศึกษา";
    private final String df_password = "รหัสผ่าน";
    private final String df_c_password = "ยืนยันรหัสผ่าน";
    private final Color tf_Focus_color = new Color(255, 255, 255);
    private final Color tf_lostFocus_color = new Color(117,105,109);
}
