package UserInterface.old;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        surnameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        studentIDRTF = new javax.swing.JTextField();
        conpasswordRTF = new javax.swing.JTextField();
        passwordRTF = new javax.swing.JTextField();
        sigupB = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        contactL1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(9, 26, 88));
        jPanel2.setPreferredSize(new java.awt.Dimension(1335, 810));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please fill in the information correctly and completely.");

        nameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nameTF.setForeground(new java.awt.Color(204, 204, 204));
        nameTF.setText("Name");
        nameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTFFocusLost(evt);
            }
        });
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        surnameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        surnameTF.setForeground(new java.awt.Color(204, 204, 204));
        surnameTF.setText("Surname");
        surnameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surnameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                surnameTFFocusLost(evt);
            }
        });
        surnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTFActionPerformed(evt);
            }
        });

        emailTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emailTF.setForeground(new java.awt.Color(204, 204, 204));
        emailTF.setText("Email");
        emailTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTFFocusLost(evt);
            }
        });
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        studentIDRTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentIDRTF.setForeground(new java.awt.Color(204, 204, 204));
        studentIDRTF.setText("Student ID");
        studentIDRTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentIDRTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIDRTFFocusLost(evt);
            }
        });
        studentIDRTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDRTFActionPerformed(evt);
            }
        });

        conpasswordRTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        conpasswordRTF.setForeground(new java.awt.Color(204, 204, 204));
        conpasswordRTF.setText("Confirm Password");
        conpasswordRTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conpasswordRTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                conpasswordRTFFocusLost(evt);
            }
        });
        conpasswordRTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpasswordRTFActionPerformed(evt);
            }
        });

        passwordRTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passwordRTF.setForeground(new java.awt.Color(204, 204, 204));
        passwordRTF.setText("Password");
        passwordRTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordRTFFocusLost(evt);
            }
        });
        passwordRTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRTFActionPerformed(evt);
            }
        });

        sigupB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sigupB.setForeground(new java.awt.Color(9, 26, 88));
        sigupB.setText("SIGNUP");
        sigupB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sigupB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigupBActionPerformed(evt);
            }
        });

        jCheckBox1.setText("I accept ");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox1.setBorderPainted(true);
        jCheckBox1.setBorderPaintedFlat(true);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("the agreement");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-invisible-w-30.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(9, 26, 88));
        jPanel5.setPreferredSize(new java.awt.Dimension(1335, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Problem?");

        contactL1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactL1.setForeground(new java.awt.Color(255, 255, 255));
        contactL1.setText("Contact the developer");
        contactL1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        contactL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactL1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactL1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactL1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(studentIDRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(passwordRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(conpasswordRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(sigupB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(614, 614, 614))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(588, 588, 588))))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIDRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conpasswordRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addComponent(sigupB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTFFocusGained
        // TODO add your handling code here:
        if (nameTF.getText().equals("Name")) {
            nameTF.setText("");
            nameTF.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_nameTFFocusGained

    private void nameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTFFocusLost
        // TODO add your handling code here:
        if (nameTF.getText().equals("")) {
            nameTF.setText("Name");
            nameTF.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_nameTFFocusLost

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void surnameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameTFFocusGained
        // TODO add your handling code here:
        if (surnameTF.getText().equals("Surname")) {
            surnameTF.setText("");
            surnameTF.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_surnameTFFocusGained

    private void surnameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameTFFocusLost
        // TODO add your handling code here:
        if (surnameTF.getText().equals("")) {
            surnameTF.setText("Surname");
            surnameTF.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_surnameTFFocusLost

    private void surnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTFActionPerformed

    private void emailTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTFFocusGained
        // TODO add your handling code here:
        if (emailTF.getText().equals("Email")) {
            emailTF.setText("");
            emailTF.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_emailTFFocusGained

    private void emailTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTFFocusLost
        // TODO add your handling code here:
        if (emailTF.getText().equals("")) {
            emailTF.setText("Email");
            emailTF.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_emailTFFocusLost

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void studentIDRTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDRTFFocusGained
        // TODO add your handling code here:
        if (studentIDRTF.getText().equals("Student ID")) {
            studentIDRTF.setText("");
            studentIDRTF.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_studentIDRTFFocusGained

    private void studentIDRTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDRTFFocusLost
        // TODO add your handling code here:
        if (studentIDRTF.getText().equals("")) {
            studentIDRTF.setText("Student ID");
            studentIDRTF.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_studentIDRTFFocusLost

    private void studentIDRTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDRTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDRTFActionPerformed

    private void conpasswordRTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conpasswordRTFFocusGained
        // TODO add your handling code here:
        if (conpasswordRTF.getText().equals("Confirm Password")) {
            conpasswordRTF.setText("");
            conpasswordRTF.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_conpasswordRTFFocusGained

    private void conpasswordRTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conpasswordRTFFocusLost
        // TODO add your handling code here:
        if (conpasswordRTF.getText().equals("")) {
            conpasswordRTF.setText("Confirm Password");
            conpasswordRTF.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_conpasswordRTFFocusLost

    private void conpasswordRTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpasswordRTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpasswordRTFActionPerformed

    private void passwordRTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRTFFocusGained
        // TODO add your handling code here:
        if (passwordRTF.getText().equals("Password")) {
            passwordRTF.setText("");
            passwordRTF.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_passwordRTFFocusGained

    private void passwordRTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRTFFocusLost
        // TODO add your handling code here:
        if (passwordRTF.getText().equals("")) {
            passwordRTF.setText("Password");
            passwordRTF.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_passwordRTFFocusLost

    private void passwordRTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRTFActionPerformed

    private void sigupBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigupBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sigupBActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void contactL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactL1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactL1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conpasswordRTF;
    private javax.swing.JLabel contactL1;
    private javax.swing.JTextField emailTF;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField passwordRTF;
    private javax.swing.JButton sigupB;
    private javax.swing.JTextField studentIDRTF;
    private javax.swing.JTextField surnameTF;
    // End of variables declaration//GEN-END:variables

}
