/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form.User;

/**
 *
 * @author USER
 */
public class AboutDeveloper extends javax.swing.JFrame {

    /**
     * Creates new form AboutDeveloper
     */
    public AboutDeveloper() {
        
        initComponents();
        
        AboutDeveloper.setText("");
        
        this.setTitle("About");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeveloperL = new javax.swing.JList<>();
        CloseB = new javax.swing.JButton();
        AboutDeveloper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        DeveloperL.setBackground(new java.awt.Color(153, 153, 153));
        DeveloperL.setFont(new java.awt.Font("FreesiaUPC", 0, 20)); // NOI18N
        DeveloperL.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "66070153 Phakin Pansook", "66070162 Phumphuridon Wongchan", "66070166 Manonthakorn Khunsuwan", "66070257 Natthajak Dilorattanaphijahit", "66070295 Pochara Sappasate", "66070305 Phuriphat Arunphaisan", "66070310 Siwat Chantarak", "66070311 Supakorn Vachirapoosit" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DeveloperL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                DeveloperLValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DeveloperL);

        CloseB.setBackground(new java.awt.Color(0, 0, 0));
        CloseB.setFont(new java.awt.Font("FreesiaUPC", 1, 24)); // NOI18N
        CloseB.setForeground(new java.awt.Color(255, 255, 255));
        CloseB.setText("Close");
        CloseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBActionPerformed(evt);
            }
        });

        AboutDeveloper.setFont(new java.awt.Font("Cordia New", 1, 22)); // NOI18N
        AboutDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        AboutDeveloper.setText("Developer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AboutDeveloper)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(CloseB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(AboutDeveloper)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CloseB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseBActionPerformed

    private void DeveloperLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_DeveloperLValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            String select = DeveloperL.getSelectedValue();
            if (select.equals("66070153 Phakin Pansook")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070153@kmitl.ac.th<br>หน้าที่: Art Director </html>");
            } else if (select.equals("66070162 Phumphuridon Wongchan")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070162@kmitl.ac.th<br>หน้าที่: Back-End Developer </html>");
            } else if (select.equals("66070166 Manonthakorn Khunsuwan")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070166@kmitl.ac.th<br>หน้าที่: Front-End Developer </html>");
            } else if (select.equals("66070257 Natthajak Dilorattanaphijahit")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070257@kmitl.ac.th<br>หน้าที่: Front-End Developer </html>");
            } else if (select.equals("66070295 Pochara Sappasate")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070295@kmitl.ac.th<br>หน้าที่: Front-End Developer </html>");
            } else if (select.equals("66070305 Phuriphat Arunphaisan")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070305@kmitl.ac.th<br>หน้าที่: Back-End Developer </html>");
            } else if (select.equals("66070310 Siwat Chantarak")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070310@kmitl.ac.th<br>หน้าที่: Front-End Developer </html>");
            } else if (select.equals("66070311 Supakorn Vachirapoosit")) {
                AboutDeveloper.setText("<html>" + select + "<br>66070311@kmitl.ac.th<br>หน้าที่: Front-End Developer </html>");
            } else {
                AboutDeveloper.setText("");
            }
        }
    }//GEN-LAST:event_DeveloperLValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutDeveloper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutDeveloper;
    private javax.swing.JButton CloseB;
    private javax.swing.JList<String> DeveloperL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
