/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form.User;

import Database.Dataclass.HistoryData;
import Database.Dataclass.RoomData;
import Database.Dataclass.TimeDate;
import Database.Exception.DatabaseGetInterrupted;
import Database.RoomDatabase;
import Firebase.UserLoginToken;
import Form.Admin.RoomEdit;

import javax.swing.*;
import java.awt.*;
import java.sql.Time;

/**
 *
 * @author Nonsan
 */
public class ViewBookingPanel extends JPanel {
    TimeDate timeDate;
    RoomData roomData;
    /**
     * Creates new form ViewBookingPanel
     */
    public ViewBookingPanel(HistoryData historyData) {
        initComponents();
        timeDate = historyData.getTimeDate();
        try {
            roomData = RoomDatabase.getRoomObject(historyData.getRecorded());
        } catch (DatabaseGetInterrupted e) {
            e.printStackTrace();
        }
        roomname_label.setText(roomData.getRoomName());

        floor_building_label.setText("Floor "+roomData.getFloor()+", "+roomData.getBuilding());

        book_time_label.setText(TimeDate.toPoint60(historyData.getTimeDate().getTime1())+"-"+TimeDate.toPoint60(historyData.getTimeDate().getTime2()));
        date_label.setText(historyData.getTimeDate().getTimeDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomname_label = new javax.swing.JLabel();
        floor_building_label = new javax.swing.JLabel();
        book_time_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();

        roomname_label.setFont(new java.awt.Font("DilleniaUPC", 1, 48)); // NOI18N
        roomname_label.setText("Roomname"); // NOI18N

        floor_building_label.setFont(new java.awt.Font("DilleniaUPC", 1, 48)); // NOI18N
        floor_building_label.setText("Floor, Building"); // NOI18N

        book_time_label.setFont(new java.awt.Font("DilleniaUPC", 0, 36)); // NOI18N
        book_time_label.setText("16:00-18:00"); // NOI18N

        date_label.setFont(new java.awt.Font("DilleniaUPC", 0, 36)); // NOI18N
        date_label.setText("12 Apr 67"); // NOI18N

        cancel_btn.setFont(new java.awt.Font("FreesiaUPC", 1, 24)); // NOI18N
        cancel_btn.setText("ยกเลิก");
        cancel_btn.setMargin(new java.awt.Insets(5, 14, 0, 14));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomname_label)
                    .addComponent(floor_building_label))
                .addGap(162, 162, 162)
                .addComponent(book_time_label)
                .addGap(168, 168, 168)
                .addComponent(date_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {floor_building_label, roomname_label});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(book_time_label)
                    .addComponent(date_label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomname_label)
                        .addGap(6, 6, 6)
                        .addComponent(floor_building_label))
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        System.out.println(roomname_label.getText()+" "+date_label.getText()+" "+book_time_label.getText());
        int choice = JOptionPane.showConfirmDialog(ViewBookingPanel.this, "Are you sure you want to cancel this reservation?\nThis action cannot be undone.", "Cancel reservation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (choice == JOptionPane.YES_OPTION) {
            RoomDatabase.cancelReservation(timeDate, roomData, UserLoginToken.getClient());
        }


    }//GEN-LAST:event_cancel_btnActionPerformed
    public JButton getCancel_btn(){return cancel_btn;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_time_label;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel floor_building_label;
    private javax.swing.JLabel roomname_label;
    // End of variables declaration//GEN-END:variables
}
